services:
  # Default configuration for services in the app
  _defaults:
    autowire: true
    autoconfigure: true

  # Define the services for controllers in the NickYeoman\SymfonyCMSBundle\Controller namespace
  NickYeoman\SymfonyCMSBundle\Controller\:
    resource: '../src/Controller/*'
    tags: ['controller.service_arguments']